# Generated by Django 3.1.7 on 2021-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(max_length=254)),
                ('cust_bal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_amt', models.FloatField()),
                ('trans_from_id', models.IntegerField()),
                ('trans_to_id', models.IntegerField()),
            ],
        ),
    ]
